name: CI Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:
    branches-ignore: [ master ]

  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: MondayHopscotch/echo/.github/composites/build@workflow-test
